### ISSUE TITLE
IP denylists: Import from local/remote

### ISSUE THREAD

**Issue by Horizonbli** [celzero/rethink-app#533] opened 2022-08-30 10:31 UTC
Unless I am missing something, is there a way to import IP denylists from local and remote files?

Thanks

**Comment by ignoramous** [comment] 2022-09-02 22:01
Nope, but see dup: #237

**Comment by ignoramous** [comment] 2022-09-07 05:15
Closing it as duplicate of #237 

Please feel free to reopen.

**Closed by ignoramous** 2022-09-07 05:15 UTC
