### ISSUE TITLE
Crash when checking for blocklist updates when no Internet connection is available

### ISSUE THREAD

**Issue by afontenot** [celzero/rethink-app#571] opened 2022-09-22 00:50 UTC
This can happen e.g. in airplane mode (for testing) or when the connection unexpectedly fails or times out (I was able to reproduce this by testing it while rebooting my router).

Repro:

1. Default settings + DNS-only mode + Cloudflare DoH
2. Download the on-device blocklists and enable a few of them.
3. Put the device in airplane mode (WiFi and cell data disabled)
4. Click "check for update" in the blocklist dropdown.

Result: RethinkDNS crashes. After doing this multiple times Android shows the "RethinkDNS keeps crashing" warning.

Device Info: Moto X4 with LineageOS 19.1 (Android 12)

----------

I discovered this crash while trying to reproduce a *different* crash (or something that seems to be a crash). Once or twice a day RethinkDNS will randomly stop working. The VPN icon will (usually) disappear from the Android taskbar at the top. When opening the app, it will be disconnected (or sometimes "failed") but then reconnect. Either something is causing the app to crash, or Android is killing it. It seemed worse when I was on a flaky cell connection, so I got the idea it could happen when a request made by the app unexpectedly failed. Any ideas about how to reproduce and isolate the problem would be appreciated.

**Comment by ignoramous** [comment] 2022-09-22 17:18
> Any ideas about how to reproduce and isolate the problem would be appreciated.

If the app wasn't killed by battery optimizer / OOM killer, there should be a detailed log in the `logcat` output. But `logcat` has a limited per-app buffer (I believe `256K`?), so, android may have captured the crash in the `bugreport` folder, which you can access either via (root) `adb shell; cd /bugreports/` or (non-root) `adb bugreport`.

What ROM are you on? On MIUI, I've seen users report crashes. On close-to-AOSP Android phones (like Pixel, OnePlus, Motorola, Asus), there are no crashes at all. The app runs for days on end just fine.

**Comment by ignoramous** [comment] 2022-09-22 17:21
> Result: RethinkDNS crashes. After doing this multiple times Android shows the "RethinkDNS keeps crashing" warning.

Thanks for the steps. I have a device unfit for testing this scenario. @hussainmohd-a will test and report back.

**Comment by afontenot** [comment] 2022-09-22 21:56
Thanks for the advice. Here's a partial logcat capturing the crash for **this** bug report (crash on blocklist update).

[com.celzero.bravedns.logcat.txt](https://github.com/celzero/rethink-app/files/9629636/com.celzero.bravedns.logcat.txt)

I haven't looked at the code closely, but it seems like I might be right that the app can crash if a connection to a DoH server unexpectedly fails. If so, this *might* explain some other crashes as well!

**Comment by afontenot** [comment] 2022-09-22 23:07
Looks like this is the problem:

https://github.com/celzero/rethink-app/blob/0e2339d/app/src/main/java/com/celzero/bravedns/download/AppDownloadManager.kt#L95

results in cycling through every built-in DoH source when there's a connection failure, so it eventually gets to the last one `SYSTEM_DNS`:

https://github.com/celzero/rethink-app/blob/0e2339d/app/src/main/java/com/celzero/bravedns/customdownloader/RetrofitManager.kt#L74

but this last method doesn't provide a client, which OkHttp seems to require, so that causes the crash. Maybe this diff would fix it:

```diff
diff --git a/app/src/main/java/com/celzero/bravedns/customdownloader/RetrofitManager.kt b/app/src/main/java/com/celzero/bravedns/customdownloader/RetrofitManager.kt
index 54d1288..a7d105a 100644
--- a/app/src/main/java/com/celzero/bravedns/customdownloader/RetrofitManager.kt
+++ b/app/src/main/java/com/celzero/bravedns/customdownloader/RetrofitManager.kt
@@ -72,7 +72,7 @@ class RetrofitManager {
                         InetAddress.getByName("2001:4860:4860:0:0:0:0:8844")).build()
                 }
                 OkHttpDnsType.SYSTEM_DNS -> {
-                    return DnsOverHttps.Builder().build()
+                    return DnsOverHttps.Builder().client(OkHttpClient()).build()
                 }
             }
         }
```

**Comment by afontenot** [comment] 2022-09-22 23:16
Important discovery: [https://github.com/celzero/rethink-app/blob/0e2339d/app/src/main/java/com/celzero/bravedns/scheduler/BlocklistUpdateCheckJob.kt#L49](BlocklistUpdateCheckJob.kt#L49) has a duplicate `isDownloadRequired` function instead of using the one in `AppDownloadManager`. And this one *always* uses `OkHttpDnsType.DEFAULT`!

This means that if you have the "prompt on blocklist updates" option enabled, you'll get a crash approximately every three days (assuming that text is right) because of this issue!

**Comment by ignoramous** [comment] 2022-09-23 04:10
Thanks. The `SYSTEM_DNS` code exists for no good reason as it does not do what it was intended for (fallback upon system dns).

In the new code, the `url` for doh is still not set, yeah? That should also result in an exception, per: https://github.com/square/okhttp/blob/118bdb28ca5a45390b730abed35ad27461ff8260/okhttp-dnsoverhttps/src/main/kotlin/okhttp3/dnsoverhttps/DnsOverHttps.kt#L254

**Comment by hussainmohd-a** [comment] 2022-09-23 06:50
Fixed the issue, will be part of the next release. 
The OkHttpClient requires the DNS not to be set in order to use the system DNS.
```

// If unset, the system-wide default DNS will be used.
customDns(dnsType)?.let { okhttpClientBuilder.dns(it) }
```

returning null, in case of system DNS.

```
OkHttpDnsType.SYSTEM_DNS -> {
    return null
}
```

**Comment by ignoramous** [comment] 2022-09-25 03:05
Fixed in dev, will released with `v053k` that's currently blocked by #572

**Closed by ignoramous** 2022-09-25 03:05 UTC
Labels: P0
