### ISSUE TITLE
v055c: editing WireGuard DNS errors out for multiple IPs

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1311] opened 2024-03-25 00:39 UTC
> While trying to test the DNS issue as you suggested (i.e. visiting 1.1.1.1 with "192.168.178.199,192.168.178.1" as DNS), I noticed that ReThink actually does not allow to enter more than one DNS manually - I get a popup "UNIQUE constraint failed: ProxyApplicationMapping.uid, Proxy..." if I try that.

_Originally posted by @Braintoe in https://github.com/celzero/rethink-app/issues/1298#issuecomment-2017003618_

**Comment by luckygitt** [comment] 2024-03-26 08:48
I found a similar issue while trying to edit the MTU in a Wireguard Config - you cannot leave the DNS blank ("Auto") -


![wireguard](https://github.com/celzero/rethink-app/assets/150080223/932e64b8-bbe8-425e-9e04-9119f9455a3f)
 it fails with an error (see screenshot)

**Comment by hussainmohd-a** [comment] 2024-03-29 11:15
> > While trying to test the DNS issue as you suggested (i.e. visiting 1.1.1.1 with "192.168.178.199,192.168.178.1" as DNS), I noticed that ReThink actually does not allow to enter more than one DNS manually - I get a popup "UNIQUE constraint failed: ProxyApplicationMapping.uid, Proxy..." if I try that.
> 
> _Originally posted by @Braintoe in [#1298 (comment)](https://github.com/celzero/rethink-app/issues/1298#issuecomment-2017003618)_

The issue is due to an incorrect call to update the proxy data in the ProxyMappingTable, which has been fixed in https://github.com/celzero/rethink-app/pull/1301/commits/6b8cdfb1cb630b4671121c05261b6d3bc38380ce.

**Closed by hussainmohd-a** 2024-03-29 11:15 UTC
Labels: bug, P0

**Comment by ignoramous** [comment] 2024-04-15 05:14
> The issue is due to an incorrect call to update the proxy data in the ProxyMappingTable https://github.com/celzero/rethink-app/commit/6b8cdfb1cb630b4671121c05261b6d3bc38380ce

How was updating the `name` breaking `DNS` config update?

**Comment by hussainmohd-a** [comment] 2024-04-15 05:27
If the name update fails, the DNS config edit will also fail because the edit operation updates all the data instead of just the changed one.
