### ISSUE TITLE
v0.5.5m: Regular timeouts across any requests

### ISSUE THREAD

**Issue by Terrance** [celzero/rethink-app#1511] opened 2024-06-04 22:28 UTC
When routing via Wireguard, I'm finding a significant proportion (maybe 10-20%) of requests time out, randomly but fairly regularly.  I can see in the logs:

```
1717539029.199 10506 30203  9127 D BatchLogger: signal wait over, sz(b: 0, u: 1) / cur-buf(7552)
1717539029.200 10506 30203  9127 D BatchLogger: transfer and swap (7552) u: 1, b: 0
1717539032.037 10506 30203  3470 I GoLog   : transport.go:574: D dns: udp: done; tot: 1, t: 120000ms, err: read udp 10.111.222.3:53: i/o timeout
1717539040.912 10506 30203  7923 I GoLog   : transport.go:574: D dns: udp: done; tot: 1, t: 120001ms, err: read udp 10.111.222.3:53: i/o timeout
1717539040.913 10506 30203  7923 I GoLog   : transport.go:574: D dns: udp: done; tot: 1, t: 120000ms, err: read udp 10.111.222.3:53: i/o timeout
1717539040.942 10506 30203  3106 I GoLog   : transport.go:574: D dns: udp: done; tot: 1, t: 120000ms, err: read udp 10.111.222.3:53: i/o timeout
1717539040.942 10506 30203  3106 I GoLog   : transport.go:574: D dns: udp: done; tot: 1, t: 120001ms, err: read udp 10.111.222.3:53: i/o timeout
1717539040.968 10506 30203  3470 I GoLog   : transport.go:574: D dns: udp: done; tot: 1, t: 120001ms, err: read udp 10.111.222.3:53: i/o timeout
1717539040.972 10506 30203  3448 I GoLog   : transport.go:574: D dns: udp: done; tot: 1, t: 120001ms, err: read udp 10.111.222.3:53: i/o timeout
1717539046.191 10506 30203  7923 I GoLog   : transport.go:574: D dns: udp: done; tot: 1, t: 120002ms, err: read udp 10.111.222.3:53: i/o timeout
1717539046.658 10506 30203  3448 D VpnLifecycle: bind: Base, 133, rinr? false
1717539046.661 10506 30203  3448 D VpnLifecycle: bind: use active network is true
1717539046.662 10506 30203  3448 I GoLog   : rdial.go:167: D rdial: commondial: confirmed ip 100.100.77.17 for 100.100.77.17:443 failed with err dial tcp 100.100.77.17:443: connect: connection timed out
1717539046.662 10506 30203  7923 E GoLog   : retrier.go:129: E rdial: tcp addr 100.100.77.17:443: err dial tcp 100.100.77.17:443: connect: connection timed out
1717539046.663 10506 30203  3448 I GoLog   : base.go:49: I proxy: base: dial(tcp) to 100.100.77.17:443; err? dial tcp 100.100.77.17:443: connect: connection timed out
1717539046.663 10506 30203  3448 I GoLog   : ipmap.go:148: I ipmap: Add: resolving 100.100.77.17
1717539046.663 10506 30203  3448 I GoLog   : ipmap.go:197: D ipmap: renew: 100.100.77.17 / seed: [] / typ: Auto
1717539046.663 10506 30203  3448 I GoLog   : ipmap.go:217: D ipmap: makeIPSet: 100.100.77.17, seed: [], typ: Regular
1717539046.663 10506 30203  3448 I GoLog   : ipmap.go:222: D ipmap: makeIPSet: 100.100.77.17 for Regular, confirmed addr 100.100.77.17
1717539046.663 10506 30203  3448 I GoLog   : ipmap.go:259: D ipmap: add: fail 100.100.77.17; !uns? true, val? true, !new? false
1717539046.663 10506 30203  3448 I GoLog   : ipmap.go:287: D ipmap: Add: resolved? 100.100.77.17 => [100.100.77.17]
1717539046.663 10506 30203  3448 I GoLog   : rdial.go:178: D rdial: renew ips for 100.100.77.17:443; ok? true
1717539046.663 10506 30203  3448 I GoLog   : rdial.go:180: D rdial: commondial: trying all ips 0 for 100.100.77.17:443
1717539046.663 10506 30203  3448 I GoLog   : rdial.go:202: D rdial: commondial: duration: 31.413515092s; failed 100.100.77.17:443
1717539046.663 10506 30203  7923 E GoLog   : tcp.go:274: W tcp: err dialing a659aadf64f233a1 proxy(Base) to dst(100.100.77.17:443) for 10532: dial tcp 100.100.77.17:443: connect: connection timed out
1717539046.664 10506 30203  7923 E GoLog   : tcp.go:233: W tcp: dial: #0: a659aadf64f233a1 failed; addr(100.100.77.17:443); for uid 10532 (31413); w err(dial tcp 100.100.77.17:443: connect: connection timed out)
```

Using the same DNS outside of WireGuard (configured as DoH on the local network; DNS and WG peer are on the same box) with the proxy disabled doesn't seem to suffer these timeouts.

I've tried removing IPv6 addresses as suggested in #1483/#1500, but that doesn't seem to have made any difference.

v055m on OnePlus Nord CE.

**Comment by ignoramous** [comment] 2024-06-05 12:47
> 1717539046.663 10506 30203  7923 E GoLog   : tcp.go:274: W tcp: err dialing a659aadf64f233a1 proxy(Base) to dst(100.100.77.17:443) for 10532: dial tcp 100.100.77.17:443: connect: connection timed out

This connection isn't using WireGuard (it says: `proxy(Base)`, which means the underlying network).

```
1717539032.037 10506 30203  3470 I GoLog   : transport.go:574: D dns: udp: done; tot: 1, t: 120000ms, err: read udp 10.111.222.3:53: i/o timeout
1717539040.912 10506 30203  7923 I GoLog   : transport.go:574: D dns: udp: done; tot: 1, t: 120001ms, err: read udp 10.111.222.3:53: i/o timeout
1717539040.913 10506 30203  7923 I GoLog   : transport.go:574: D dns: udp: done; tot: 1, t: 120000ms, err: read udp 10.111.222.3:53: i/o timeout
1717539040.942 10506 30203  3106 I GoLog   : transport.go:574: D dns: udp: done; tot: 1, t: 120000ms, err: read udp 10.111.222.3:53: i/o timeout
1717539040.942 10506 30203  3106 I GoLog   : transport.go:574: D dns: udp: done; tot: 1, t: 120001ms, err: read udp 10.111.222.3:53: i/o timeout
1717539040.968 10506 30203  3470 I GoLog   : transport.go:574: D dns: udp: done; tot: 1, t: 120001ms, err: read udp 10.111.222.3:53: i/o timeout
1717539040.972 10506 30203  3448 I GoLog   : transport.go:574: D dns: udp: done; tot: 1, t: 120001ms, err: read udp 10.111.222.3:53: i/o timeout
1717539046.191 10506 30203  7923 I GoLog   : transport.go:574: D dns: udp: done; tot: 1, t: 120002ms, err: read udp 10.111.222.3:53: i/o timeout
```
These are not timeouts, but rather socket within Rethink that received all but a single-use UDP packet (`tot: 1`) from Android's caching stub DNS resolver (`dnsmasq`) in the 2mins (`120002ms`) that it was listening for more.

**Comment by Terrance** [comment] 2024-06-05 19:04
Apologies, tried to get a snippet on-device so plausibly missing something -- will grab a full log when I'm back at a computer.

**Comment by Terrance** [comment] 2024-06-05 22:39
Ok, having spent some time tinkering, it seems this happens whether proxying with WireGuard or not.  The original testing and log snippet was done with WireGuard connected, but with it only routing internal IPs so not the requests I was testing with.

This may be a v0.5.5m regression, as I think the F-Droid release date (3 days ago) coincides with when I started toying with the various WireGuard options.

📎 [2024-06-05-22-18-38_216.snip.log](https://github.com/user-attachments/files/15597358/2024-06-05-22-18-38_216.snip.log)

Here's a more complete log of Termux repeatedly running `curl https://example.com` (I've replaced the logs around a couple of unrelated queries with `...`).  There are a handful of timeouts in there, which match up to either 30 second delays in the response, or 1 minute delays before curl gives up with `curl: (35) Recv failure: Connection reset by peer`.

**Comment by diegol88** [comment] 2024-06-06 16:44
I also have the problem you guys are reporting and only found the 0.5.5i stable.

**Comment by ignoramous** [comment] 2024-06-06 20:15
> I switched from [v0.5.5h] to [v0.5.5m] and can feel like there is alot of times where a connection to website in chrome stall and dont load, than I cant connect to any website, like there is some kind of overall lag

Worrying. Over WireGuard or just the underlying network?

> I had also problems with stopping the firewall (some kind of stall, lag where its "stopping" for 10 seconds)

As in, you tap on "STOP" button in Rethink's homescreen (or toggle the Rethink STOP/START notification tile) and Rethink simply waits for a long time?

**Comment by ignoramous** [comment] 2024-06-07 00:25
> This may be a v0.5.5m regression, as I think the F-Droid release date (3 days ago) coincides with when I started toying with the various WireGuard options.
> 
> 📎 [2024-06-05-22-18-38_216.snip.log](https://github.com/user-attachments/files/15597358/2024-06-05-22-18-38_216.snip.log)

Thanks. What you're seeing is a bug  introduced by a commit in #1431 (which ironically, also fixed this bug with https://github.com/celzero/firestack/commit/027f9fd2b324b9d4822e80c5aa02896711d4c621 but reintroduced it with https://github.com/celzero/firestack/commit/d944e61507833634549e897a0e57204dfc5722cb for cases when *Advanced DNS filtering* is turned ON).

**Comment by diegol88** [comment] 2024-06-07 18:47
> > This may be a v0.5.5m regression, as I think the F-Droid release date (3 days ago) coincides with when I started toying with the various WireGuard options.
> > 📎 [2024-06-05-22-18-38_216.snip.log](https://github.com/user-attachments/files/15597358/2024-06-05-22-18-38_216.snip.log)
> 
> Thanks for the logs! What you're seeing is a bug introduced by a commit in #1431 (which ironically, also fixed this bug with [celzero/firestack@027f9fd](https://github.com/celzero/firestack/commit/027f9fd2b324b9d4822e80c5aa02896711d4c621) but reintroduced it with [celzero/firestack@4b232a0](https://github.com/celzero/firestack/commit/4b232a0ee2dc89191fef04ba5c2bc27b0408643f) for cases when _Advanced DNS filtering_ is turned ON).

I can confirm that without Advanced DNS filtering, the latest release works well for me.

**Comment by Terrance** [comment] 2024-06-07 20:07
I've had _Advanced DNS filtering_ switched off today, and indeed that also seems to have resolved the timeouts for me.

**Comment by puelp** [comment] 2024-06-09 10:43
I've had Advanced DNS filtering off for a few days now, and the timeouts have NOT been fixed for me.

(Version 0.5.5m)

**Comment by ignoramous** [comment] 2024-06-09 11:39
> the timeouts have NOT been fixed for me

- Do only select websites / apps timeout?
- Any singular app / website for which timeouts happen consistently?
- Have you changed any setting in *Configure* -> *Network*?
- What status do you see in *Network Logs* for connections that do timeout?
   - Tap on entries that you suspect are timing out, and a *bottomsheet* should come up.
   - The *footer* of that *bottomsheet* usually displays final status of that connection.

Can you put Rethink in *Very Verbose* from *Configure* -> *Settings* -> *Log level*, then capture the logs when the timeout happens?

**Comment by puelp** [comment] 2024-06-09 12:49
Do only select websites / apps timeout?
    Any singular app / website for which timeouts happen consistently?

On my main profile, it happens mostly with Mull, the hardened Firefox fork that I use: https://f-droid.org/packages/us.spotco.fennec_dos/
All websites time out/refuse to load the first time I try to access them. Then, after a few seconds/minutes, I reload the page, and it loads fine.

On my Insular work profile: https://f-droid.org/en/packages/com.oasisfeng.island.fdroid/
it happens across all apps (shopping, maps, banking, etc.)
Same as above. Content refuses to load the first time. So I wait, and then it loads fine.

    Have you changed any setting in Configure -> Network?

I'm not sure what the default settings are.
I have lockdown mode enabled, so the first three settings (visibility, forwarder, private) are grayed out.
Then, I have the next two settings (use all, loopback) turned off.
Then, I have fallback DNS set to Cloudflare (main DNS is RethinkDNS), and IP version set to IPv4 (default).
The settings are the same for the Rethink on my main profile, and the cloned Rethink on my Insular work profile.

    What status do you see in Network Logs for connections that do timeout?
        Tap on entries that you suspect are timing out, and a bottomsheet should come up.
        The footer of that bottomsheet usually displays final status of that connection.

Just now, I opened up Mull and typed in a random address. I immediately got an "Address Not Found" page.
I opened up Rethink.
On the main Rethink page, I see "NO INTERNET" in pink below the [STOP] button. As I was typing this, it turned back into "PROTECTED" in blue.
I go into Logs->Network but there isn't anything related to the page that I just tried to open in Mull.
I go back into Mull and reload the page. Still get an "Address Not Found" error.
I wait another minute and reload the page again. The page finally loads, like three minutes after the initial attempt to access it.

Can you put Rethink in Very Verbose from Configure -> Settings -> Log level, then capture the logs when the timeout happens?

Is the log data 100% anonymous and safe to post online??

**Comment by ignoramous** [comment] 2024-06-09 13:25
Thanks.

Seems like on your Android, DNS is cooked.

> I go into Logs->Network but there isn't anything related to the page that I just tried to open in Mull.

Check DNS Logs (but the footer there usually says "no error" even if there are errors; a bug we've since fixed in [`v055n`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5n)).

> Is the log data 100% anonymous and safe to post online??

**Comment by puelp** [comment] 2024-06-09 14:12
So is it a problem with my phone? Does that mean that the issue is unfixable?

OK, I will wait for 0.5.5n to hit F-Droid and see if the issue still persists on 0.5.5n. IF it does, I will send you logs.

**Comment by najjara** [comment] 2024-06-14 06:08
The issue is not yet resolved in v055n.
It times out badly when advanced filtering is on, and when IPv6 or Auto are selected almost no connections go through

**Comment by ignoramous** [comment] 2024-06-14 10:43
> times out badly when advanced filtering is on, and when IPv6 or Auto are selected almost no connections go through

Please capture logs (`adb logcat`)
and share them if you know how.

Please note that both *IPv6*[^f] and *Advanced DNS filtering* are experimental features. And we can't resolve these bugs if we don't know what's going on (since we don't see these ourselves).

[^f]: for IPv6-only mode to work, the underlying network (mobile, wifi, usb, etc) must have IPv6.

**Comment by ignoramous** [comment] 2024-06-14 10:53
@Terrance can you please check if you still see this timeout issue? `v055n` is out on F-Droid: https://f-droid.org/packages/com.celzero.bravedns/

**Comment by Terrance** [comment] 2024-06-14 11:13
Update came through this morning -- have re-enabled both advanced DNS filtering and auto IP version, can't immediately reproduce any timeouts here (through regular use, or by repeating the Termux testing from before which is happily using both protocols).  🙂

Will keep an eye on it in case it doesn't manifest straight away...

**Comment by najjara** [comment] 2024-06-14 16:55
@ignoramous should I enable all the relevant settings first, then capture, or start capturing before anything?

**Comment by najjara** [comment] 2024-06-14 17:06
I went to capture the logs, and for now I can't reproduce it (short term).
I'll keep an eye on it. The previous version wasn't timing out all the time on all requests. I'll have to wait.

**Comment by ignoramous** [comment] 2024-06-14 17:47
> should I enable all the relevant settings

Enable *Very Verbose* or *Verbose* from *Configure* -> *Settings* -> *Log level*. The rest of the app settings should be as per your preference (the reason I asked u/Terrance to enable *Auto* (IP version) and *Advanced DNS filtering* is they originally reported issue with using those settings).

**Comment by najjara** [comment] 2024-06-17 05:39
I has reappeared so far. Maybe it was that one time.

**Comment by ignoramous** [comment] 2024-06-17 10:13
> It has reappeared so far. Maybe it was that one time.

hasn't*?

**Comment by najjara** [comment] 2024-06-18 06:09
> > It has reappeared so far. Maybe it was that one time.
> 
> hasn't*?

Sorry, typo. Has NOT.

**Comment by ignoramous** [comment] 2024-06-18 08:36
Thanks for the confirmation 😅

Closing. Do feel free to reopen in case this happens again. For a related issue (timeouts/misroute) with *Advanced DNS filtering*, see #1546

**Closed by ignoramous** 2024-06-18 08:36 UTC
Labels: bug
