### ISSUE TITLE
Profile For Different Connections

### ISSUE THREAD

**Issue by gitusercodes** [celzero/rethink-app#342] opened 2021-07-27 18:26 UTC
I use RethinkDNS since a while, and it is great, but I have a request

A possibility in RethinkDNS for different Firewall profiles would be a huge improvement
I mean with different profile for example a profile for mobile connection and a Wifi profile
like the Netguard Firewall has
https://play.google.com/store/apps/details?id=eu.faircode.netguard
See Settings
https://play-lh.googleusercontent.com/aVFfQpb8KfuKangXyZgP70s0zfSPSBV-6FDl0GclSsgT4839zfn0doygH1AL0f-VeabX=w720-h310-rw
The Firewall without root has also a possibility for 2 profiles Wifi and mobile connection
https://play.google.com/store/apps/details?id=app.greyshirts.firewall
https://play-lh.googleusercontent.com/F_pp0A38rbwYPZPwU9mPS4e5xSR-qwxNJCvvapKIXpg_nQaBU4f0lHHjRs1y2FmOGd-A=w720-h310-rw

If I am connected with mobile, I want to block more apps to save data traffic
(Here are mobile connection still expensive) and at the moment with RethinkDNS
it is painful always to change the settings from the apps (Allow or block)
With profiles that would save a lot of time

In Telegram people suggest cloning the app and always start a different RethinkDNS app
but that solve not the problem and is very inconvenient

**Comment by ignoramous** [comment] 2021-07-27 21:04
The functionality to enable / disable blocks based on wifi and mobile already has been implemented but the UI constraints have forced us to not expose it to users. For example, an app today can be either `whitelisted`, `excluded`, `firewalled`, `allowed`. Adding `wifi` and `mobile` to these states requires a different UI to the one exists today, that we are yet to build. We do not like how NetGuard and NoRoot expose these today with a bunch of icons. Not that RethinkDNS itself is a beacon of great UI, but that just our opinion.

Also, instead of differentiating as `mobile` and `wifi` we were thinking users likely want to instead differentiate between `metered` (typically, `mobile` or prepaid `wifi`) and unmetered (typically, office or home `wifi`) connections.

Would your request be duplicate of #127?

**Comment by gitusercodes** [comment] 2021-07-27 21:25
Thank you for the explanation. The idea from metered and unmetered is an interesting approach.

This leads me to the suggestion of making the profiles more generic and leaving it up to the user to decide which apps are in which profile and what the purpose is.
This could lead to a much more accurate setting because it would make sense to have more than only 2 profiles.
E.g.
1) Home
2) In Office
3) Commuting to the Office
4) Whatever
The user can then decide which profile he wants to use (Maybe in another additional step with time based possibilities)

If you searching for someone for testing profiles, please let me know


> Would your request then be a duplicate of #127?
I had not read #127 before, but it is slightly different

**Comment by ignoramous** [comment] 2021-07-27 21:44
> This leads me to the suggestion of making the profiles more generic and leaving it up to the user to decide which apps are in which profile and what the purpose is.

This requires us to nail the UI or it would get confusing pretty quick. Besides, allowing this much customization might force us to first implement import / export (user settings backup) because database corruption does happen.
1. #165 
2. #343 

So, it will be quite a while before this feature makes it in. #127 is likely to make it in sooner.

**Comment by ignoramous** [comment] 2022-11-11 21:41
Also: https://github.com/celzero/rethink-app/discussions/635

**Comment by ItsIgnacioPortal** [comment] 2023-03-03 14:51
This seems to have been implemented now. This issue was just left behind :p

**Comment by ignoramous** [comment] 2023-03-03 19:27
Thanks. 

@gitusercodes pls feel free to reopen in case what's implemented today (in `v053n`) isn't what you were expecting.

**Closed by ignoramous** 2023-03-03 19:27 UTC
