### ISSUE TITLE
Some feeds are blocked in AntennaPod

### ISSUE THREAD

**Issue by woj-tek** [celzero/rethink-app#964] opened 2023-08-03 16:57 UTC
It's starting to driving me nuts, while RethingDNS is enabled some feeds from AntennaPod are blocked, for example: http://api.rtve.es/api/programas/23730/audios.rss

I tried disabling everything in RethingDNS  (Sky/ RDNS Plus - edit, deselect any list, apply) but still nothing. 
Then I went to "Rules", Configuration and again disabled all rules - nothing, still error in AntennaPod

**I disabled "Rules" completely and switched to "System DNS" at which point RethinkDNS should basically do nothing and it is still not working.**

I restored the configuration and added AntennaPod to Permint/Exclude lists (my understanding is that it should not do anything to AP requests in that case) and it's not working.

At this point only completely disabling RDNS works...

**Comment by ignoramous** [comment] 2023-08-04 11:51
Thanks.

I don't use AttenaPod, but realise that it is super popular. I'll test it one of these days.

AtennaPod is open source, yeah? It might be worth while asking the developers if AtennaPod is incompatible with local VPNs like Rethink.

**Comment by woj-tek** [comment] 2023-08-04 11:56
Yes, AntennaPod is open source. I don't think it shouldn't be compatible with local VPNs. Besides, the problem is only with a couple of feeds, not all of them, which would suggest a rule being triggered (but I wasn't able to track which rule or where it was)

**Comment by woj-tek** [comment] 2023-08-04 12:02
I shared one of them in the first message: http://api.rtve.es/api/programas/23730/audios.rss

Is there some sort of cache that would cause similar issue?

**Comment by ignoramous** [comment] 2023-08-10 19:09
> Is there some sort of cache that would cause similar issue?

Android caches dns responses. Ideally, stop / start Rethink should clear those up.

Rethink also caches, if *DNS Booster* is enabled by the user (in v054, it is disabled by default). Tapping on the "refresh" icon in the DNS screen (top right of the screen) rids of the existing cache.

**Comment by woj-tek** [comment] 2023-08-11 05:42
> Android caches dns responses. Ideally, stop / start Rethink should clear those up.

Stop/starting Rethink didn't help.

I have Booster disabled.

Though, since yesterday I don't see the error. It's weird...

**Comment by Terrance** [comment] 2023-08-14 19:01
Having dug the media URL out of AntennaPod's database backup and thrown it into curl, I can see there's an additional redirect from `chrt.fm` to `traffic.megaphone.fm`, where the latter is blocked by upstream DNS (I run a local [Blocky](https://github.com/0xERR0R/blocky) DNS server with a couple of blocklists, and Rethink is configured to use it via DoH).

I guess the question then is why Rethink isn't showing this domain anywhere in the UI -- I would expect it to appear in the DNS panel as blocked by upstream?

**Comment by woj-tek** [comment] 2023-08-16 14:13
Slightly extending the scope - I just tried accessing https://jedynka.polskieradio.pl/artykul/1128364,Poradnik-wyborczy-sprawdz-czy-jestes-w-spisie-wyborcow in Firefox (and Vivalding) and got network error. Rethink reported that websited is permitted... disabling Rethink and I was able to open it... there is something fishy going on here...

**Comment by ignoramous** [comment] 2023-08-16 16:06
> Rethink reported that websited is permitted... disabling Rethink and I was able to open it... there is something fishy going on here...

Do you have *DNS Booster* enabled? In [`v055`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5) (not yet available on the PlayStore / F-Droid but should be in the coming days), we've fixed a grave bug where the DNS cache data was incorrectly stored in some very rare cases.

**Comment by woj-tek** [comment] 2023-08-16 16:32
https://github.com/celzero/rethink-app/issues/964#issuecomment-1674237254

> I have Booster disabled.

⬆️ no, I don't have booster from what I see :-)

**Comment by ignoramous** [comment] 2023-08-16 17:39
Right... I can reproduce the issue with `jedynka.polskieradio.pl`. `cURL` on my PC loads it just fine while Chrome / Firefox with Rethink enabled can't.

My theory is `jedynka.polskieradio.pl` doesn't like TLS `ClientHello` packet split Rethink does  ([ref](https://github.com/celzero/firestack/blob/1483271613a5f39b0e0871be0bee8ea5f3a97f24/intra/tcp.go#L364))... I have a fix for this in mind and will see if it works and report back. Might take a while though.

**Comment by woj-tek** [comment] 2023-08-19 11:12
I updated to the latest version yesterday and today got update from rtve feed so it seems something got fixed.

polskie radio is still inaccesible though.

**Comment by ignoramous** [comment] 2023-08-19 19:10
> polskie radio is still inaccesible though.

https://github.com/celzero/firestack/commit/eecc66827551dae63555efd5d579683277cf4980 has the fix. Will ship with v055a (hopefully, in two days from now as there are other severe bugs like #991 and #992).

**Comment by ignoramous** [comment] 2023-09-08 21:07
Thanks a bunch everyone for helping us track this one down. It was really one of the more satisfying bugs to track down.

[`v055a`](https://www.reddit.com/r/rethinkdns/comments/166m2rd/v055a_a_glitch_in_the_matrix/) has the fix. Please see if AntennaPod (feeds) work for you folks without any problems with Rethink enabled? If so, reopen this bug and we would be happy to take another look.

**Closed by ignoramous** 2023-09-08 21:07 UTC
Labels: bug, P0

**Comment by Terrance** [comment] 2023-09-08 21:12
Just to confirm (as it looks like a few of us may have reported some subtely different issues), my issue of upstream blocks not being reported is indeed fixed in v055a (now showing in the DNS tab of logs).  :+1:
