### ISSUE TITLE
v055d: IPv4 websites do not open in Auto mode

### ISSUE THREAD

**Issue by Sinestr0** [celzero/rethink-app#1325] opened 2024-04-02 17:36 UTC
Many weird things going on after latest update, v055d. after the latest update, dns+firewall mode was (is still) active, IP version was auto, no universal rules set (default setting), and many websites just stop opening like startpage.com and apps like session messenger stopped getting connected. Most of connections are showing up in logs as unknown. I tested by switching to netguard and everything again started working fine. 

I am trying to further digging up by different settings in rethink app and will report here.

EDIT : Followings are my findings.

I tested on specifically website startpage.com and session app as they seemed to be not working properly as above i mentioned, both of them were working fine with netguard or without any firewall at that time. But many other websites like wikipedia were opening fine while having above mentioned issue.

Startpage.com and session messenger were working well with dns+firewall, dns, firewall modes with network set to ipv4.

Startpage.com with ipv6 and firewall mode was working well, but with ipv6 and dns mode, it couldn't get opened at all, either shows unreachable error or address not found error.

Session messenger with ipv6 didnt work at all with either dns or firewall mode.

Moreover, whenever any connection is made through ipv6, it shows "unknown" in "network" in logs.

I do not remember facing any such issues with previous version. Please verify or try to reproduce this issue.

Also another complaint for previous version (couldn't test properly for latest version), it uses too much battery, like around 40% in single charge and medium usage of phone with around 4 hours of screentime and single day use.

**Comment by ignoramous** [comment] 2024-04-02 20:10
>  But many other websites like wikipedia were opening fine while having above mentioned issue.


> Moreover, whenever any connection is made through ipv6, it shows "unknown" in "network" in logs.

What version of Android are you on? On Android 8 and below these bugs have been reported before:
- #821 

> it uses too much battery, like around 40% in single charge 

Sounds bad, but I've heard one or two people say this. Typically, battery use shouldn't go beyond 15%. On my Androids, it hovers between 5% to 15% (never beyond that).

- Can you post a screenshot of the usage, if you're comfortable doing so?
- Does this happen consistently or just happened this one time?
- *Force Stop* Rethink and start it back up again, and see if this 40% usage persists?

> Session messenger with ipv6 didnt work at all with either dns or firewall mode.

See if any of the domains used by the Session Messenger are blocked in *DNS Logs* due to user-set rules? If not, check *Network Logs* and see why the connections from the Session Messenger are failing:
- Search for the app from the search bar in *Network Logs* UI.
- See if the connections are blocked (these show up with a red colour left-hand side border).
- See if the connections are failing (zero upload / download) (tap on entries to reveal a *bottomsheet*; the footer of that *bottomsheet* would show the final status of the connection).

> Startpage.com and session messenger were working well with dns+firewall, dns, firewall modes with network set to ipv4.

Continue using *IPv4*. It is hard for us to know what's going on on your network and Android unless you share more. If you're technical enough:
- Is there something specific to your networking setup or the network provider with regards to dual-stack (some network providers run 6to4 translations services, for example; and we don't know if Rethink breaks on such networks)?
- Logs captured via `adb logcat` from when this issue happens.

Note: *Auto* is experimental. I must say though, it works for me just fine.

**Comment by ignoramous** [comment] 2024-04-02 20:17
> I'm suddenly having this issue too when using 5G instead of Wi-Fi 

We've seen reports of broken IPv6 before on earlier Rethink versions, too: #554 

- If you're in *Auto* mode, is *Perform connectivity checks* enabled or disabled (in *Configure* -> *Network*)?
- When this issue happens, can you see if you're able to:
   - Visit `ipv6only.me` in Chrome: If it doesn't load, do you see "resolution error" or any other error (such as "timeouts").
   - Visit `ipv6.me` in Chrome: If it loads, do you see it show a IPv4 address or an IPv6 address?

**Comment by ignoramous** [comment] 2024-04-03 10:16
Thank you for your detailed reply 🙏

---

*DNS-only* mode seems broken. I can verify that. Unsure why, but we are looking.

As for the email, I haven't got any. In your email, please mention this GitHub issue. My email is, `mz` at `celzero` dot `com`.

As for your other issues, it seems like the websites that don't work with Rethink in *IPv6* mode are IPv4-only websites (`startpage.com`). This is expected.

You can test your network by visiting from a browser:
- `ip4.me`: Loads only if there's IPv4 connectivity
- `ip6.me`: Loads if there's IPv4 *or* IPv6 connectivity.
- `ip6only.me`: Loads only if there's IPv6 connectivity.

**Comment by ignoramous** [comment] 2024-04-03 17:23
> Auto in Configure > Networks > Choose IP Version? Does it automatically decide if the connection should be IPv4 or IPv6?

Yes.

> which means I have IPv6 connectivity already right?

Yes.

> if it can not get connected to IPv4, then problem might be there

Yes.

> works but ip4.me shows either connection time out or endlessly loading

This seems similar to the issue also discussed at #554

- Is Rethink in *VPN Lockdown* mode (that is, is *Block connections without VPN* from Android Settings app turned ON)?
- Is *Perform connectivity checks* enabled when in *Auto* mode?
    - If not, *enable* it and see if `ip4.me` loads?
    - If so, *disable* it, and see if `ip4.me` loads?
- Would you know how to grab output from `adb logcat`?
- And execute `adb shell` commands?

I presume this happens on Mobile and not Wifi?

**Comment by ignoramous** [comment] 2024-04-04 10:00
> "80: connect: connection timed out"

What was the destination IP address in the status?

> somehow on brave, it shows error for connection timeout or it is just loading endlessly

Browsers have a DNS cache of their own. Sometimes, force stopping them and restarting them back up makes them whole.

> I am not sure what else I did. I was just turning off on-device blocklist for the battery usage test but then turned it on again when I figured out I can visit ip4.me

So: I guess this problem isn't there anymore... like at all? Then, it might be related to #1330  / #991 related error (it can manifest in strange ways).

**Comment by AnonymousWP** [comment] 2024-04-04 12:46
I've been very busy the last few days, so sorry for the late reply. I still need to read everything in this thread. If possible (in case my logs/info isn't necessary anymore) I'd prefer to try to fix it without me. If that's not possible, let me know.

**Comment by ignoramous** [comment] 2024-04-04 14:19
> Is that fix already implemented? if yes, then this issue was related to that

It has been, but your version doesn't yet have it. Also, the bug #1330 manifests in weird ways with *Auto* mode and DNS blocklists. And I think it is the cause of what you saw, as well.

We'll release `v055e` shortly fixing just that bug.

---

@AnonymousWP Understandable. Do not share if you don't want to. No pressure. And probably wait for `v055e` which may potentially fix what you're seeing.

**Comment by ignoramous** [comment] 2024-04-07 11:17
Thanks. I'll close this.

Others: Please feel to reopen if you see similar symptoms to what's discussed here (it has been a long discussion).

**Closed by ignoramous** 2024-04-07 11:17 UTC
Labels: bug
