### ISSUE TITLE
reinstall result in unnamed apps

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#769] opened 2023-02-05 02:46 UTC
A user says,

> I had an exchange app and I deleted it. After a while I had to reinstall it. I believe this unnamed application was the exchange application in an older version that was cached.
>
> Every time I used the exchange application it appeared as blocked by the firewall and to get it working again I had to unblock the exchange application and this unnamed app as well (both were necessary).
>
> I did everything but the only way that worked was to delete the rethinkdns data. After that I redid the settings and the unnamed app was no longer on the firewall. And the exchange app was no longer automatically blocked.

Additional details: No Work Profile. And there wasn't an OS update in the interim.

Version: v053n

Sounds like both db and cache related cleanups after uninstalls may need to be revisited.

**Comment by hussainmohd-a** [comment] 2023-06-22 19:46
As of v055, the residual data of uninstalled apps will be removed when the Rethink's app refresh job is executed or when the user manually clicks on the 'Refresh Apps' option from the app UI. Now, before inserting a new app, all residual apps will be removed, which was the cause of the above-mentioned issue (both new app and residual app with the same UID). Closing this issue for now. It will be reopened if any issues are reported after the release of v055.

**Closed by hussainmohd-a** 2023-06-22 19:46 UTC
Labels: bug, P1

**Comment by ignoramous** [comment] 2023-06-22 22:00
Commit that fixed this?

**Comment by hussainmohd-a** [comment] 2023-06-23 10:19
Ref: https://github.com/celzero/rethink-app/commit/413c91482756f1fc0f8538b0649c67bc0bd19917, https://github.com/celzero/rethink-app/commit/5614bcfeba3184b6b35e47029067aaccaf9aa21f
