### ISSUE TITLE
WireGuard connection not possible

### ISSUE THREAD

**Issue by luk6173** [celzero/rethink-app#1081] opened 2023-10-02 06:03 UTC
Hi,

I setup a WireGuard connection to my FRITZ!Box and after connecting to it, I get always this error:

`ParseAddr("fritz.box"): unexpected character (at "fritz.box")`

With WireGuard App it works fine.

Regards
Lukas

**Comment by ignoramous** [comment] 2023-10-02 09:28
Ah, thanks. Looks like it is expecting an IP address, but hostnames (`fritz.box`) should work too.

Can you please share the full stack trace?

**Comment by ignoramous** [comment] 2023-10-02 09:50
Okay, the code isn't expecting a hostname as DNS addresses. We will fix this pronto.

> Sure, but can you tell me how to create a full stack trace?

Usually with `adb logcat` *as* you're hitting this problem, if you're technical enough. If not, emailing us the "bug report" from Rethink app's *About* UI works too. In this case though, I realise where the problem is, and the fix is straight forward; so expect it to land it in the next imminent release, `v055b` (3 to 5 days away).

**Comment by ignoramous** [comment] 2023-10-02 09:52
Btw, WireGuard DNS is not utlizied. We are fixing this through:

1. #979
2. #1069 
3. #1013 
4. #1014

**Comment by luk6173** [comment] 2023-10-02 09:54
Bug report sent via E-Mail. Thank you very much :)

**Comment by hussainmohd-a** [comment] 2023-10-03 14:04
From logs
```
proxy: wg: failed to get addrs from config ParseAddr("fritz.box"): unexpected character (at "fritz.box")

connect-tunnel: could not start wireguard go.Universe$proxyerror: ParseAddr("fritz.box"): unexpected character (at "fritz.box") at ipn.Ipn$proxyProxies.addProxy(Native Method)
```

**Comment by ignoramous** [comment] 2024-03-21 17:16
We've since fixed adding hostnames as DNS address for WireGuard in `v055b`: https://github.com/celzero/firestack/commit/2ea4501082fe463805225208b36ea8d9ee8a57b6

For `fritz.box` in particular, the address must be resolvable by whatever the current user-set DNS is (probably, one might want to set it to "System DNS" if expecting `fritz.box` to be resolved by the local network only). If the domain ended with `.local` (ex: `fritz.local`), then Rethink would have used "System DNS" automatically for such queries.

**Closed by ignoramous** 2024-03-21 17:16 UTC
Labels: bug
