### ISSUE TITLE
dns leak? 

### ISSUE THREAD

**Issue by anxiouslelimo** [celzero/rethink-app#1236] opened 2024-03-03 05:07 UTC
checked via browserleaks.com. prevent dns leaks toggled on.

0.55a & 0.55b shows additional google servers.

![Screenshot_20240303-101624_Firefox](https://github.com/celzero/rethink-app/assets/115996455/c72a7402-2e6e-47a9-8942-55c74b360418)

**Comment by ignoramous** [comment] 2024-03-03 06:26
What DNS is the app set to?

**Comment by ignoramous** [comment] 2024-03-03 16:29
Can you retry the tests with Android's built-in *Private DNS* to see if you get the same result? I'm unable to reproduce the leaks.

**Comment by ignoramous** [comment] 2024-03-03 17:36
> Curiously i toggled off "Show website icon in dna logs" and now it just shows nextdns.

Ah, yeah. dns leak tests end up confused when Rethink sends additional requests to download icons.

I'll close this issue then. Feel free to reopen this one or report other bugs. Thanks.

**Closed by ignoramous** 2024-03-03 17:36 UTC
