### ISSUE TITLE
[Wireguard] Traffic not routed if IP not in Allowed IPs

### ISSUE THREAD

**Issue by lichenscon** [celzero/rethink-app#1140] opened 2023-11-14 21:17 UTC
I am using a Wireguard VPN to connect to my home and Tailscale/Headscale network. Therefor i only want specific subnets routed via Wireguard (in my example 100.64.0.0/10). This is working in official Wireguard app by adding only this subnet to the allowed IPs so no other traffic is routed via VPN. 

When using Rethink also only the allowed traffic is routed via VPN, but other traffic is blocked silently. If i am changing the allowed IPs to 100.64.0.0/0, all traffic is routed through VPN as expected. Therefor my public IP-adress is the one of my peer, which is static and would give me less privacy.
I think this behavior could also be a feature, but the user must be able to turn it off.

**Comment by ignoramous** [comment] 2023-11-16 22:49
I am surprised Tailscale works with default WireGuard as-is? We've have an open issue on it #1047 

> When using Rethink also only the allowed traffic is routed via VPN, but other traffic is blocked silently. f i am changing the allowed IPs to 100.64.0.0/0, all traffic is routed through VPN as expected.

I think I understand what you mean (and we could fix it)... but can you reword this / be more clear so I know for sure?

**Comment by lichenscon** [comment] 2023-11-16 23:46
> I am surprised Tailscale works with default WireGuard as-is? We've have an open issue on it #1047

No, I am using a seperate Wireguard-Server as a Tailscale-Gateway because of too high battery drain of Tailscale. 

> > When using Rethink also only the allowed traffic is routed via VPN, but other traffic is blocked silently. f i am changing the allowed IPs to 100.64.0.0/0, all traffic is routed through VPN as expected.
> 
> I think I understand what you mean (and we could fix it)... but can you reword this / be more clear so I know for sure?

If I am setting the allowed IPs in my Wireguard config to 100.64.0.0/10 and an app is trying to connect to 188.114.96.3, the traffic is blocked and neither routed via Wireguard or my local network connection. Connections to 100.64.0.45 are routed via WG as expected. So only traffic that is allowed to pass the VPN is routed (via the VPN), all other traffic (that should be routed via local network) is discarded.

**Comment by ignoramous** [comment] 2023-11-17 16:45
Gotcha. This has been this for in the upcoming version `v055b` (we'll release it in a week or so once we get to the bottom of a frequent crash in our network engine, that remains elusive).

**Comment by ignoramous** [comment] 2024-03-02 22:42
Fixed in [`v055b`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5b).

https://github.com/celzero/rethink-app/blame/02c16a99764b82bd4fbcc53187134cf944c47931/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L2699

**Closed by ignoramous** 2024-03-02 22:42 UTC
Labels: bug

**Comment by hegdenischay** [comment] 2024-07-28 06:02
Hi, I have this same issue. It works on the android wireguard client, same as the OP, but doesn't work on RethinkDNS. Any way I can test this on my machine?

Version: 0.5.5n (fdroid)

**Comment by ignoramous** [comment] 2024-07-28 13:55
> It works on the android wireguard client, same as the OP, but doesn't work on RethinkDNS. 

What works?

**Comment by hegdenischay** [comment] 2024-07-28 14:38
I'm using this kind of config in RethinkDNS:

```
[Interface]
Address = 192.168.13.2/24
ListenPort = 31337
PrivateKey = <redacted>

[Peer]
PublicKey = <redacted>
AllowedIPs = 192.168.13.0/24
Endpoint = <server>:<port>
PersistentKeepalive=10
```

But it looks like it's routing all traffic through the wireguard endpoint instead of just IPs like 192.168.13.1

Not sure if I'm doing something wrong here.

**Comment by ignoramous** [comment] 2024-07-28 15:36
> But it looks like it's routing all traffic through the wireguard endpoint instead of just IPs like 192.168.13.1. 

Are you running WireGuard in *Simple* mode or *Advanced* mode?

Can you check Configure -> Logs -> Network Log to see if traffic to other IPs are also sent through "Proxy".

If you're technical enough, can you switch to *Very verbose* in *Configure* -> *Settings* -> *Log level* and tail `adb logcat | grep -iE "(vpnlife|golog)"` output to see what it prints (or share it with me over email `mz` at `celzero` dot `com`)?

**Comment by hegdenischay** [comment] 2024-07-28 16:47
Thanks for the specific adb logs that I needed to troubleshoot this. It turns out that I wasn't tunnelling the DNS IP through the wireugard `AllowedIPs` section (note the lack of `1.1.1.1/32` in there). So now connections outside the VPN work well. However, I'm not able to connect to any of the `192.168.13.0/24` IPs now.

To answer the rest of your questions, I'm using Simple mode, and it appears that DNS is tunnelled through the VPN regardless of whether `AllowedIPs` is `0.0.0.0/0` or not. 

Just to note, I wasn't able to connect to them before either, so this part isn't a regression. I am still able to access them with Wireguard on Android just fine, so this might be due to some kind of tweaking that that app does.

My current config is something like this now:

```
[Interface]
Address = 192.168.13.2/24
PrivateKey = <redacted>

[Peer]
PublicKey = <redacted>
AllowedIPs = 192.168.13.0/24, 1.1.1.1/32
Endpoint = <server>:<port>
PersistentKeepalive=10
```

**Comment by hegdenischay** [comment] 2024-07-28 17:09
I finally figured it out! I had set "Do not route Private IPs" in the Network settings. That + allowing DNS through the VPN fixes my issues.

**Comment by ignoramous** [comment] 2024-07-28 18:38
Thanks for the reporting back. Glad it works the way you expect it to.

Btw, you could consider removing the KeepAlive for power/battery reasons.

Rethink has many footguns...
