### ISSUE TITLE
Crash on start since 0.5.5d

### ISSUE THREAD

**Issue by PurpleVsGreen** [celzero/rethink-app#1345] opened 2024-04-06 08:17 UTC
After updating the Android application, it keeps crashing whenever I run it.
I grabbed a log with matlog.

[2024-04-06-10-03-22.txt](https://github.com/celzero/rethink-app/files/14892926/2024-04-06-10-03-22.txt)

The box runs crDroid 10.2 which is Android 14.

I tried downgrading but it still crashes.

**Comment by acutbal** [comment] 2024-04-06 08:31
Hello,
I have the same problem, the Play Store version crashes when start. However, the F-Droid version and the apk available on the RethinkDNS don't have such issue.
My device is a Poco F5 with stock HyperOS.

Regards.

**Comment by hussainmohd-a** [comment] 2024-04-06 08:42
The issue appears to be caused by the Play Store library. It has been fixed and will be included in the next release. As a temporary workaround, you can use version v055d from the website.

**Comment by PurpleVsGreen** [comment] 2024-04-06 09:13
*Makes note never to use Aurora Store*

`Thank you guise \./`

**Comment by ignoramous** [comment] 2024-04-06 17:35
> Makes note never to use Aurora Store

**Comment by ignoramous** [comment] 2024-04-06 17:36
obl

**Closed by ignoramous** 2024-04-06 17:36 UTC
