### ISSUE TITLE
Fine tuning app instead of adding buggy features 

### ISSUE THREAD

**Issue by allmightyasian** [celzero/rethink-app#911] opened 2023-05-19 05:40 UTC
Please for god sake, stop adding features for a while and make current one work properly, 
Vpn and other things can wait, please make it more efficient, in battery and data aspects

**Comment by ignoramous** [comment] 2023-05-19 18:25
Hi there,

We already went through a massive 8 month rewrite to arrive at this point (#282 / #354). So it isn't that we don't take stability seriously. We do. The VPN feature should have otherwise landed in June 2021 (which it still hasn't)!

It is disappointing to hear that the app isn't stable. What issues are you seeing in particular? Are you okay with sharing [bugreports](https://developer.android.com/studio/debug/bug-report) (at the time of crashes) with us over email (I am `mz` at `celzero` dot `com`)?

As for battery use, what do your ROM's battery stats tell you? Anything beyond 10% is concerning. On my Android 12 device, Rethink doesn't go beyond 3%. 

Usually, battery use is a function of firewall rules. It could be that installed apps are hammering away at the firewall in a bid to get its connections out. When you spot such apps, *Force Stop* them. Rethink cannot *Force Stop* these for you, since Google removed that API citing security reasons (rightly so).

A tip: If you have any app on `Bypass DNS & Firewall`, you can instead switch all of them to `Bypass Universal` / `Exclude` instead. The firewall works a tad differently for *all* apps when *any* app is `Bypass DNS & Firewall`.

**Comment by allmightyasian** [comment] 2023-05-21 16:54
First of all a well a refined ui will be better,
For example there are two sections of firewall in homepage, one universal page for one feature will be good, again its your choice im not the one to talk,
As for battery usage this version is better than previous one, but the thing i don't like about this update, is you can use domain filtering only with rethink dns, if there's a way to improve it please do it, thanks for responding

**Comment by ignoramous** [comment] 2023-05-21 17:07
Only *trust*ing (allowing) domains works with rdns better. It should work with other dns upstreams, but it may not work; that's a guarantee we can't give (for example, if Quad9 / AdGuard decides to block a domain you've *trust*ed (allowed), the app won't override it). The current version only makes that more explicit since a lot of folks were confused why *trust*ing domains didn't work for other dns upstreams.

The UI bit will improve over time (or, so I hope). We aren't great at UI, but I'd appreciate specific examples of what could be improved #834

**Comment by mervyn-mccreight** [comment] 2023-10-08 22:13
> As for battery use, what do your ROM's battery stats tell you? Anything beyond 10% is concerning. On my Android 12 device, Rethink doesn't go beyond 3%.

It's about 29% at the moment for me.

**Comment by ignoramous** [comment] 2023-10-08 23:32
> about 29% at the moment for me.

I'd expect it to be this high only if WireGuard / SOCKS5 / HTTP proxying or PCAP (*Configure* -> *Settings* -> *Packet Capture*) is enabled.

Are you using on-device blocklists? We have long *suspected* that it might cause power drain, but we haven't yet found any concrete reports of it.

Some users have reported that turning OFF *Configure* -> *Settings* -> *Enable on-device logging* improved battery life dramatically (we are unsure why or how).

**Comment by allmightyasian** [comment] 2023-10-09 04:26
> > about 29% at the moment for me.
> 
> I'd expect it to be this high only if WireGuard / SOCKS5 / HTTP proxying or PCAP (_Configure_ -> _Settings_ -> _Packet Capture_) is enabled. Or, the _Universal_ rule "Block any app not in use" turned ON (it uses Android's built-in _Accessibility Service_ which is super expensive in terms of resources it consumes).
> 
> Are you using on-device blocklists? We have long _suspected_ that it might cause power drain, but we haven't yet found any concrete reports of it.
> 
> Some users have reported that turning OFF _Configure_ -> _Settings_ -> _Enable on-device logging_ improved battery life dramatically (we are unsure why or how).
> 
> Generally though, power drain is also a function of installed apps and rules. Some apps try frantically to connect to the Internet when firewalled / denied. You can spot such heavy hitting apps in the "Stats" section on "Most blocked apps". I usually _Force Stop_ such apps.

Well after new update surprisingly it's working normal

**Comment by mervyn-mccreight** [comment] 2023-10-09 06:47
> > about 29% at the moment for me.
> 
> I'd expect it to be this high only if WireGuard / SOCKS5 / HTTP proxying or PCAP (*Configure* -> *Settings* -> *Packet Capture*) is enabled. Or, the *Universal* rule "Block any app not in use" turned ON (it uses Android's built-in *Accessibility Service* which is super expensive in terms of resources it consumes).
> 
> Are you using on-device blocklists? We have long *suspected* that it might cause power drain, but we haven't yet found any concrete reports of it.
> 
> Some users have reported that turning OFF *Configure* -> *Settings* -> *Enable on-device logging* improved battery life dramatically (we are unsure why or how).
> 
> Generally though, power drain is also a function of installed apps and rules. Some apps try frantically to connect to the Internet when firewalled / denied. You can spot such heavy hitting apps in the "Stats" section on "Most blocked apps". I usually *Force Stop* such apps.

Yes I use on device blocklists.
I'll check the stuff you said and see if any of it reduces battery drain.

**Comment by mervyn-mccreight** [comment] 2023-10-09 06:54
I wasn't using most of the stuff you mentioned. I deactivated storing the logs for now and see if that helps. If not, I'm going to activate it again and deactivate the on device blocklists.

**Comment by mervyn-mccreight** [comment] 2023-10-10 12:36
Deactivating the local storage of logs seemed to change nothing.

Deactivating the local blocklists (I was using 5, I can share the link if that helps) brought the consumption down to 19%, which is still pretty high IMO. It might also be caused by my usage of the phone, but the nearly 30% was independent of my personal usage behavior as far as I could see.

I'll have a closer look at the third thing you mentioned (firewall).

**Comment by ignoramous** [comment] 2024-05-18 21:03
We've since employed static and dynamic analysis to improve the stability of the app, and continue to fix bugs/crashes as they get reported.

It is always a struggle to keep the app bug free (missing tests are one big reason for this, but we haven't got the bandwidth to add tests today) as every new major feature we add, ends up in us having to change a bulk of what was there before.

Closing this issue as it is too meta and fit for a "discussion" instead.

Thanks for your feedback folks, much appreciated (and keep it coming).

**Closed by ignoramous** 2024-05-18 21:03 UTC
