### ISSUE TITLE
Trust domains does not work

### ISSUE THREAD

**Issue by efficientwrite** [celzero/rethink-app#1297] opened 2024-03-19 16:17 UTC
Trust domains not working.

Blocked domains marked as trusted in DNS tab. After stopped and started VPN connection DNS is showed as resolved but there is no entry in network tab and also corresponding data does not load.

Using version 0.5.5c from F-droid.

**Comment by hussainmohd-a** [comment] 2024-03-19 16:29
Hi @efficientwrite,

Thank you for your report. Just to ensure that I understand the issue correctly:

- It seems that domains marked as trusted, are shown as trusted in the Network tab but blocked in the DNS tab.

- After restarting the VPN connection, DNS resolution is set as allowed in the DNS tab. However, entries are not showing up in the Network tab, and the corresponding content is not loading. 


Is my understanding correct?

**Comment by ignoramous** [comment] 2024-03-20 09:03
> After trusting domain, it should work but it does not. In DNS tab, it shows as resolved but there is no entry in network tab,

For which app? Can you check if the trusted domain not visit-able from the browser, too?

**Comment by ignoramous** [comment] 2024-03-21 10:19
Just tried and *trust*ed domains worked fine (both per-app, universal/global rules). Without logs, it isn't possible to debug what you're seeing, unfortunately.

**Closed as completed** 2024-04-06 12:10 UTC
Labels: bug

**Comment by ignoramous** [comment] 2024-04-06 14:44
The problem specifically was that when a single IP had multiple rules, rules weren't working as intended.

Fix released in [`v055e`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5e). Feel free to reopen if it isn't fixed for you.
