### ISSUE TITLE
v055a: DoH does not work when WireGuard is enabled

### ISSUE THREAD

**Issue by NotMainstream** [celzero/rethink-app#1216] opened 2024-02-09 06:55 UTC
When a user uses a VPN profile he cannot use any of the DNS sources inside the app.
The only solution that seems to work right now seems to be to add a custom DNS in the Android Network settings but in this case the DNS logs in the app show just the Custom DNS hostname instead of the individual file.

**Comment by ignoramous** [comment] 2024-02-09 16:41
Hi, can you please elaborate more. It isn't clear what the issue is.

**Comment by NotMainstream** [comment] 2024-02-09 16:53
So, I added a wireguard VPN from file and the internet would not work with any DNS option from the RethinkDNS app. The only way it would work was if I go in to the Android Network settings and add as a custom DNS the Adguard DNS address.
Let me know if it's clear enough.

**Comment by ignoramous** [comment] 2024-02-10 07:31
Wow, strange.

- Just to be clear, you're using WireGuard from within Rethink, correct?
  - If so, you are able to use other DNSes without WireGuard in Rethink?
  - What about *System DNS* when WireGuard is enabled? Does that not work, either?

**Comment by NotMainstream** [comment] 2024-02-10 07:39
1. Yes, I use Wireguard from within RethinkDNS APP
2. Yes, all the DNSs from RethinkDNS work normally without Wireguard
3. Custom DNS ( dns.adguard.com) in Android Network Settings works when using Wireguard (this is how I'm using it right now)

**Comment by NotMainstream** [comment] 2024-02-10 07:46
If I select OFF at Private DNS in Android Network settings and in the RethinkDNS app I select a DNS andthen  I make a DNS leak test on browserleaks.com it shows the DNS from my real ISP

**Comment by ignoramous** [comment] 2024-02-10 10:28
Did you try *System DNS* with WireGuard enabled? Did that work?

Also, what version of Rethink are you? (See the bottom of the *About* UI)

**Comment by NotMainstream** [comment] 2024-02-10 10:34
App version 0.55a downloaded from GitHub on one device and on another device through F-Droid.
Yes, every time I have to select System DNS from Settings > DNS Settings in the RethinkDNS app otherwise the internet doesn't work at all when using Wireguard.

**Comment by ignoramous** [comment] 2024-02-10 10:37
Thanks. This is something we don't see ourselves. If you're technical enough,

1. Turn ON *Verbose* logging from *Configure* -> *Settings* -> *Log Level*.
2. Start capturing logs via `adb logcat`.
3. Switch to a DNS that doesn't work with WireGuard.
4. Capture and share logs over email `mz` at `celzero` dot `com` (mention this bug).

**Comment by NotMainstream** [comment] 2024-02-10 11:57
I cannot do right now the logcat as I'm not at home right now, but I can tell you that I disabled the custom DNS in Android and used the RethinkDNS for DNS and the internet worked but I could see on browserleaks.com/DNS my local country DNS in the list and after I restarted the phone with the same settings the internet stopped working at all until I have enabled again the custom DNS in Android settings. Also, for some reason WhatsApp and Facebook logs in RethinkDNS shows that every few connections it makes a connection towards an IP with my country flag but when I check those IPs with whois.com it shows that they are registered in other countries.

**Comment by ignoramous** [comment] 2024-02-10 14:02
>  IP with my country flag but when I check those IPs with whois.com it shows that they are registered in other countries.

Rethink uses a free geo-ip location database by `db-ip.com` which isn't fully accurate (their paid data is perhaps more accurate).

> I cannot do right now the logcat as I'm not at home right now

Please do so whenever you get the chance. We are not able to reproduce the issue you describe here, and hence have no clue what could be causing it.

**Comment by ignoramous** [comment] 2024-03-10 17:01
This should have been fixed in `v055c` which is live on [Play Store](https://play.google.com/store/apps/details?id=com.celzero.bravedns) and our [Website](https://rethinkdns.com/download).

Please feel free to reopen if that is not the case. Thanks.

**Closed by ignoramous** 2024-03-10 17:01 UTC
Labels: bug
