### ISSUE TITLE
v055d: Cannot add Universal IP & Port rules

### ISSUE THREAD

**Issue by nightznero** [celzero/rethink-app#1336] opened 2024-04-04 20:20 UTC
``Firewall``->``IP & Port Rules``->
**+** (plus button) doesn't work at version v055d on both section; _IP Rules_ and _Domain Rules_

**Comment by hussainmohd-a** [comment] 2024-04-05 12:33
@nightznero, Could you please provide more details? Are you experiencing issues with the dialog box not appearing when clicking the + (plus) button? Are there any error messages displayed? Additionally, please specify the Android version affected by this issue. 
A screen recording would be greatly appreciated. Thank you!

**Comment by nightznero** [comment] 2024-04-05 14:22
> @nightznero, Could you please provide more details? Are you experiencing issues with the dialog box not appearing when clicking the + (plus) button? Are there any error messages displayed? 

No no,not at all,there is no error or any crash but just button doesn't respond to clicks

> Additionally, please specify the Android version affected by this issue. A screen recording would be greatly appreciated. Thank you!

A13 OneUI 5.1

**Comment by hussainmohd-a** [comment] 2024-04-05 14:46
Thank you, @nightznero. Could you please confirm if you encounter a similar issue when attempting to add a custom domain in the DoH screen? Navigate to Configure -> DNS -> Other DNS -> DoH, then tap the + (plus) button to add a custom domain. Please let me know if you observe the same behavior there. 

If custom dialogs are not appearing on your phone, we will investigate and work on a potential fix.

**Comment by nightznero** [comment] 2024-04-05 14:51
> Thank you, @nightznero. Could you please confirm if you encounter a similar issue when attempting to add a custom domain in the DoH screen? Navigate to Configure -> DNS -> Other DNS -> DoH, then tap the + (plus) button to add a custom domain. Please let me know if you observe the same behavior there. 

Yeah, same issue on DoH and DoT as well

**Comment by hussainmohd-a** [comment] 2024-04-06 11:44
I've implemented a fix, but I'm unsure if it completely resolves the issue. This fix will be included in the next release. Please let us know if the issue persists after updating. https://github.com/celzero/rethink-app/pull/1342/commits/99c7b9158bee8256343688036958b08c3acd6d4a

**Comment by hussainmohd-a** [comment] 2024-04-07 10:02
@nightznero implemented a potential fix in v055e, now available on the [website](https://rethinkdns.com/download) and [GitHub](https://github.com/celzero/rethink-app/releases/tag/v0.5.5e). Please test it to see if the issue is resolved.

**Comment by nightznero** [comment] 2024-04-07 19:21
> @nightznero implemented a potential fix in v055e, now available on the [website](https://rethinkdns.com/download) and [GitHub](https://github.com/celzero/rethink-app/releases/tag/v0.5.5e). Please test it to see if the issue is resolved. 

Helloz thanks for ping,I didn't had time before to install and test but now after install and check...well... buttons still doesn't work,pressing and no windows pops up,another fix nedded

**Comment by hussainmohd-a** [comment] 2024-04-08 11:10
@nightznero, Thank you for the update. Could you please confirm if you are able to see the Authors dialog in the About screen?

**Comment by nightznero** [comment] 2024-04-08 14:55
> @nightznero, Thank you for the update. Could you please confirm if you are able to see the Authors dialog in the About screen?

Whats new,check for updates and authors working properly

**Closed** 2024-04-24 19:40 UTC
Labels: bug, P0
