### ISSUE TITLE
Unable to start after Re-Installing Rethink DNS

### ISSUE THREAD

**Issue by lucidtanooki** [celzero/rethink-app#673] opened 2022-11-17 23:24 UTC
Hi there,

it gets a bit complicated here. Let me explain:

1. I installed Rethink DNS
2. I enabled Rethink DNS
3. I activated Always-on VPN in Android's VPN settings
4. I uninstalled Rethink DNS (VPN profile got removed this way)
5. I re-installed Rethink DNS
6. Tapping on "Start"

Now I get a message "Always-on VPN is enabled for Rethink. Are you sure you want to stop Rethink anyway?"

1. Tapping settings does not work as there is no VPN profile yet
2. Tapping cancel does nothing
3. Tapping "Stop" does nothing as well

There seems to be some information stored that there was a VPN profile with "always-on" active. But since it's not there anymore I am stuck because I cannot change that.

Any idea how to solve this?

Best regards,
LucidTanooki

**Comment by hussainmohd-a** [comment] 2022-11-18 09:18
Hi, Thanks for reporting the issue. I tried reproducing the same in my device but its working as expected. Can you please help with more details like screenshot, android version and device?

**Comment by lucidtanooki** [comment] 2022-11-20 10:14
Unfortunately I cannot give a screenshot. Android version was 9 (LineageOS 16), Device was Samsung Galaxy Tab S2.

I resetted the device in the meantime.

But I had a similar issue on other devices. I wanted to start rethink but it told me I cannot stop it when always-on is enabled.

I'll report when I have good reproduction steps.

**Comment by ignoramous** [comment] 2022-11-22 16:01
I can't reproduce this on my Android device running OxygenOS either. I have a feeling that this issue might be specific to Lineage. Have you tried this any other VPN app?

**Comment by ignoramous** [comment] 2022-12-06 18:16
Hi, closing this since I think this issue may be specific to Lineage (which means the OS is doing something it shouldn't). Please feel free to reopen if Lineage isn't at fault (for ex, you're able to reproduce this issue on another ROM, or the Lineage developers have rejected the claim that its their issue). Thanks.

**Closed by ignoramous** 2022-12-06 18:16 UTC
