### ISSUE TITLE
Wildcard IP rules no longer work

### ISSUE THREAD

**Issue by Terrance** [celzero/rethink-app#1289] opened 2024-03-15 19:15 UTC
(Regression since `v055a`.)

I have existing IP rules of the form `*.*.*.*:<port>` and `0:0:0:0:0:0:0:0:<port>` (inputted as `[::]:<port>`) to permit requests to any IP on an app-specific port, but in `v055c` these no longer seem to work.

Earlier, I tried recreating the rules in the forms above, but _Invalid IP address, subnet or port_ was shown when trying to complete the trust rules.  I've just tried again now though it seems to be happy saving them (though they still don't permit requests), so I'm not sure what changed.

Creating rules for an individual IP or a smaller range (e,g. `[x.y.z.0/24]:<port>`) seems to work, but `[0.0.0.0/0]:<port>` does not.

**Comment by Terrance** [comment] 2024-03-15 19:33
> _Invalid IP address, subnet or port_

<img src="https://github.com/celzero/rethink-app/assets/4025899/33dc4a13-b424-4a02-92e1-c7e9e9e17998" width="300">

Just figured this out: it's because editing an IPv4 rule removes the square brackets required to create it in the first place -- the field is filled with `0.0.0.0/0:<port>` as shown in the list, but must be edited to `[0.0.0.0/0]:<port>`.

**Comment by Terrance** [comment] 2024-03-15 19:36
For now I have worked around fully-wild rules not working by splitting into two `/1` subnets which seems to work:
- `0.0.0.0/1` and `128.0.0.0/1`
- `::/1` and `7fff::/1`

**Comment by ignoramous** [comment] 2024-03-15 22:46
> For now I have worked around fully-wild rules not working

I tested this just now, adding rule on default addr w/ TLS port `[0.0.0.0/0]:443` did work. Is it not working for you?

> the field is filled with 0.0.0.0/0:<port> as shown in the list, but must be edited to [0.0.0.0/0]:<port>.

ack. Can see this. Will fix it, thanks.

**Comment by ignoramous** [comment] 2024-03-15 23:26
Okay, `[0.0.0.0/0]:443` rule added to a specific app did nothing.

**Comment by Terrance** [comment] 2024-03-15 23:51
Weird, the `/1` rules I made earlier also don't seem to be working now.  😕  (All per-app rules rather than global ones.)

With debug logging enabled, I can see for each request a set of three lines like these:
```
1710545790.422 10506 18941 14400 I GoLog   : tcp.go:192: I tcp: gconn ae83e640d290d0d6 firewalled from 10.111.222.1:40988 -> 149.154.167.91:5222 (dom:  + / real: ) for 10478; stall? 6s
1710545790.424 10506 18941 14400 I GoLog   : alg.go:735: D alg: dns64: algip(149.154.167.91) -> realips([]) -> unnated([])
1710545790.425 10506 18941 14400 I GoLog   : tcp.go:105: D onFlow: no realips() or domains( + ), for src=10.111.222.1:49958 dst=149.154.167.91:443
```
(not sure which comes first as these are being logged repeatedly)

**Comment by ignoramous** [comment] 2024-03-24 23:33
This was painful but we've fixed it.

The root cause was, our network engine (golang) and UI (kotlin) did not agree on semantics of the wildcard in IP addresses.

**Comment by hussainmohd-a** [comment] 2024-04-02 11:53
v055d (live on [GitHub](https://github.com/celzero/rethink-app/releases/tag/v0.5.5d) and [Website](https://rethinkdns.com/download)). Feel free to reopen if you still face this issue.

**Comment by Terrance** [comment] 2024-04-04 19:30
So I've updated to v055d and put my `/0` rules back, but they still don't seem to be effective, or at least I had them working initially but then they stopped working after a while -- force-closing and restarting both Rethink and the target app doesn't seem to help, and I'm seeing the same lines in the log as shown in https://github.com/celzero/rethink-app/issues/1289#issuecomment-2000686376 if that's relevant.

**Comment by ignoramous** [comment] 2024-04-04 21:37
Can you clarify please: What's the rule? A `/0`? And when you say "don't seem to be effective" what IPs you were expecting that it didn't block?

**Comment by Terrance** [comment] 2024-04-04 21:59
Using Telegram as an example -- here are the complete set of rules, the IP ones being the same as from the original issue:

<img src="https://github.com/celzero/rethink-app/assets/4025899/e235a9d8-f9ab-403b-9cfb-c0b073688e25" width="300"> 

<img src="https://github.com/celzero/rethink-app/assets/4025899/0e6d766c-4987-4422-a50d-83fe2f3cd547" width="300"> <img src="https://github.com/celzero/rethink-app/assets/4025899/9bc7b37c-ca28-4fdc-9447-4a535f80a4d4" width="300">

(the domain block rules here should be a no-op under _Isolate_; they linger from previously just accepting the _Allow_ rule)

And the resulting logs:

<img src="https://github.com/celzero/rethink-app/assets/4025899/d7a316d6-5df9-4140-9469-ab21b5bc59b6" width="300"> <img src="https://github.com/celzero/rethink-app/assets/4025899/8a2d6a98-5f2d-41f5-953c-b77e4a6c7142" width="300">

The domain rules appear to be working as intended (here permitting an embedded YouTube player), but all bare IPs are being blocked despite the IP rules (in the logs, `HTTP`/`HTTPS`/`TCP` are ports 80/443/5222 respectively) with _Isolate_ as the reason (which I assume means it's getting the default behaviour of the mode and ignoring the IP rules).

**Comment by ignoramous** [comment] 2024-04-04 23:07
> The domain rules appear to be working as intended (here permitting an embedded YouTube player), but all bare IPs are being blocked despite the IP rules (in the logs, HTTP/HTTPS/TCP are ports 80/443/5222 respectively) with Isolate as the reason (which I assume means it's getting the default behaviour of the mode and ignoring the IP rules).

This mean, port-only rules simply don't work (which is strange cause I swear to God I tested these rules before releasing `v055d`). 

I can reproduce this bug. We'll prioritize fixing it. Things that don't work, from my limited testing:
- If for Chrome `:443` is set to "no rule", it bypasses Universal `:443` block rule (it shouldn't).
- If for Chrome, `:443` is set to "block" or "allow", it isn't respected at all; but instead Universal `:443` rule applies.
- Wildcard addresses (such as `0.*.*.*:443`) which are unsupported are not replaced with (`[0.0.0.0/0]:443`) like they should.

**Comment by ignoramous** [comment] 2024-04-07 11:24
Fixed in [`v055e`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5e) as part of #1297 

The issue was, when there were multiple rules against the same IP (or IP prefix), the code only applied *none* of them. Even our tests indicated at that and we somehow missed it! 

Complicating matters was the new translation layer which converts `*` in IPs to CIDR notation kind of imperfectly (even today). On that front, we are at our wits end trying to make it work for ALL cases...

Thanks for the through bug reports that make these bugs easier to fix.

(closing this issue, please feel free to reopen in case [`v055e`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5e) doesn't fix it for you).

**Closed by ignoramous** 2024-04-07 11:24 UTC
Labels: bug, P0

**Comment by ignoramous** [comment] 2024-04-11 13:53
Thanks for your thorough bug reports. ngl, embarrassing that it took me multiple attempts to get it right...
