### ISSUE TITLE
Wireguard app config bug

### ISSUE THREAD

**Issue by mecoolk1** [celzero/rethink-app#1019] opened 2023-08-24 11:07 UTC
there's a bug when using  more than one wireguard configuration on rethink latest version.If I add more than one wireguard config and select which apps have to bypass the VPN it works for the current wireguard profile but when I do the same on the second profile and activate it the first profile app bypass is reset to zero tested on 3 devices android 13 all have the same issue rethink keeps app config only for one wireguard profile switching to another server/profile resets app to 0 and have to reconfigure manually each time

**Comment by hussainmohd-a** [comment] 2023-08-24 12:18
Hi @mecoolk1, Thank you for reporting the issue. 

I am guessing you are adding the same app to both VPN profiles. However, if you add the app to the second WireGuard profile, then the app is removed from the first profile's list. Is my understanding right? If this is the case, WireGuard profiles are designed in a way that any given app can be a part of only one WireGuard profile, regardless of whether the profile is active or not. Please correct me if I'm not getting it right.

**Comment by mecoolk1** [comment] 2023-08-24 18:54
ok I will try explain another way lets say I add 2 wireguard config one for a server in the USA and one for a server in Italy(could be for any server really) by default the profile set to 0 the apps that go through the VPN wireguard and I am ok with that(would be more helpful if all apps where set to go through the VPN by default thought just a suggestion) now I select all apps on one profile to go through the USA wireguard VPN excluding lets say just a banking app a email app and one of my 3 browser I activate the profile all works great...now I want to go to the Italy VPN server so I turn off the USA server activate the Italy server profile select the apps I want to go through the Italy VPN(not necessarily the same apps) everything works fine but now my USA wireguard profile apps are all gone from the configuration so if I switch back to the USA profile I have to start from scratch and reselect once again what apps I want to send through that vpn....and this happens Everytime I switch from one profile to the other (the regular wireguard app would save and remember the apps that go through each profile no problem once setup the first time  so I could switch on the fly from one server to another. Rethink DNS instead when switching from one wireguard profile to another one forgets all the apps that were set to go or bypass the VPN and reset itself to 0). Hope this makes it a little cleared it's basically not saving the app list (allowed/bypass) in each profile when switching from one profile to the other it resets the app list to 0

**Comment by mecoolk1** [comment] 2023-08-24 19:16
ok I just re-read your comment and yes it's li like you said if I select one app in one profile then the same app is removed from the other wireguard profile. But this implementation makes honestly no sense as I would want to send lets say all system apps through the VPN on the active profile not just on one profile otherwise it defeats the purpose of having a VPN in the first place ( one profile would protect my privacy the other wouldn't ) I would want the same apps like browsers system apps etc to always go through the VPN no matter what profile/location I select to be active. The regular wireguard client allows me to do just that (minus the dns filters firewall etc.)  that is a serious flaw in the way rethink has implemented wireguard if this is the case (cannot have the same apps on different profiles). Another issue is that switching from one VPN profile to another fails 100% of times IPC error 98 (port error etc.) way I can bypass that is switching off one profile stop rethink DNS start it again and activating other profile .... again regular wireguard client has no issues switching from one profile to another on the fly.

**Comment by ignoramous** [comment] 2023-08-24 23:27
Thanks for your suggestions.

> But this implementation makes honestly no sense as I would want to send lets say all system apps through the VPN on the active profile not just on one profile

You're looking for: #1014 (we intend to implement this on priority).

> The regular wireguard client allows me to do just that (minus the dns filters firewall etc.) that is a serious flaw in the way rethink has implemented wireguard if this is the case (cannot have the same apps on different profiles).

With Rethink, you can enable multiple profiles at once. So, if Rethink supported adding the same app to 2 or more profiles and if all those profiles were *active* at the same time, which profile should Rethink route the app traffic through?

> Another issue is that switching from one VPN profile to another fails 100% of times IPC error 98 (port error etc.)

This happens due to two separate issues. We know the cause of one of those, which we have already fixed. Researching the fix for the second.

> again regular wireguard client has no issues 

The official WireGuard app for Android is *very* different to Rethink. There isn't much similarity apart from the UI (: I also expect Rethink to be less mature given its implementation of WireGuard new and raw. Growing pains...

**Comment by mecoolk1** [comment] 2023-08-25 01:01
**You're looking for: https://github.com/celzero/rethink-app/issues/1014 (we intend to implement this on priority)**

That's great news 👍🏻

- With Rethink, you can enable multiple profiles at once. So, if Rethink supported adding the same app to 2 or more profiles and if all those profiles were active at the same time, which profile should Rethink route the app traffic through?

I actually didn't realize that as I was getting the error when switching from one profile to the other so I assumed, my mistake, that only one wireguard profile could be active at any given time the ability to have multiple wireguard VPN  tunnels running at the same time is actually quite convenient so my suggestion is if multiple profile are active at the same time and lets say the same app was active on different profiles the traffic should be routed to the top wireguard profile ( you could give the option to order the wireguard profiles so rethink would route the app traffic on the first wireguard profile the app is listed in and ignore the other profiles.

- This happens due to two separate issues. We know the cause of one of those, which we have already fixed. Researching the fix for the second.

good to know that it wasn't anything I was doing wrong I tried all kinds of configs before reporting it as a bug looking forward to a fix in the meantime turning off rethink and turning it back on solves it although leaves the device unprotected for a small amount of time, I don't want to use android Killswitch as I find it unreliable. Maybe implementing a Killswitch in rethink would be  a good solution also as a feature to have in the future 😊

- The official WireGuard app for Android is very different to Rethink. There isn't much similarity apart from the UI (: I also expect Rethink to be less mature given its implementation of WireGuard new and raw. Growing pains...

rethink is already awesome I give you guys credit for the work it's quite impressive and something I have been looking for in android for a long time! growing pains are normal and looking forward to the improvements you guys will surely make down the line keep up the good work it's really appreciated !

**Comment by ignoramous** [comment] 2023-08-25 11:12
>  multiple profile are active at the same time and lets say the same app was active on different profiles the traffic should be routed to the top wireguard profile

We thought about it, but found this setup quite confusing in practice. It is much simpler if an app is either part of a profile or not, in terms of debugging connectivity issues (because no where in the app is it shown just which VPN / Proxy an app was tunneled within). Either ways, tracking your suggestion here: https://github.com/celzero/rethink-app/issues/1023 (we may or may not implement it).

> I tried all kinds of configs before reporting it as a bug looking forward to a fix in the meantime turning off rethink and turning it back on solves it 

Tracked here: https://github.com/celzero/rethink-app/issues/1015

> Maybe implementing a Killswitch in rethink would be a good solution also as a feature to have in the future

You mean, when a VPN tunnel is turned OFF, the traffic from apps routed through it should be dropped, yeah? If so, this can get quite confusing with #1015 (where an app could be part of multiple profiles). 

> rethink is already awesome I give you guys credit for the work it's quite impressive

Appreciate it. Thanks 🙏

**Comment by ignoramous** [comment] 2023-08-28 08:21
Closing this, as from this feedback here, we've opened several more issues and are tracking them individually. Feel free to re-open in case you think we missed opening an issue for anything discussed here. Thanks once again.

**Closed by ignoramous** 2023-08-28 08:21 UTC
